 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/11-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/11-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/12-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/12-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/12-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/12-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/13-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/13-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/13-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/13-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/06-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/06-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/06-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/06-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/07-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/07-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/07-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/07-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/08-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/08-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/09-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/09-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/09-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/09-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/08-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/08-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/02-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/02-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/02-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/02-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/03-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/03-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/03-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/03-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/04-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/04-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/04-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/04-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/05-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/05-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/05-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m27/allele_seq/05-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/12-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/12-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/12-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/12-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/13-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/13-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_1/fastq/13-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/13-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/06-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/06-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/06-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/06-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/07-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/07-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/07-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/07-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/08-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/08-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/09-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/09-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/09-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/09-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_2/fastq/08-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/08-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/02-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/02-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/02-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/02-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/03-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/03-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/03-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/03-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/04-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/04-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/04-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/04-RNA_L1_2.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/05-RNA_L1_1.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/05-RNA_L1_1.fq.trim
 ln -s $ROOTSTOCK/rna-seq/RNAseq_3/fastq/05-RNA_L1_2.fq.gz.trimmed.fq $ROOTSTOCK/allele/m116/allele_seq/05-RNA_L1_2.fq.trim
